FROM nvcr.io/nvidia/deepstream:3.0-18.11
MAINTAINER Luis Bracamontes braca51e@gmail.com

RUN apt-get update && apt-get install -y \
    build-essential cmake \
    libgstreamer1.0-dev libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav libgstreamer-plugins-base1.0-dev \
    gstreamer1.0-doc gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-pulseaudio \
    libx11-dev libgstrtspserver-1.0-dev \
    wget unzip yasm libswscale-dev libtbb2 libtbb-dev \
    libjpeg-dev libpng-dev libtiff-dev libavformat-dev libpq-dev \
    python-pip \
    && rm -rf /var/lib/apt/lists/*
