FROM nvcr.io/nvidia/deepstream:3.0-18.11
MAINTAINER Luis Bracamontes braca51e@gmail.com

RUN apt-get update && apt-get install -y \
    build-essential cmake \
    libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev \
    libgstrtspserver-1.0-dev libx11-dev \
    python-pip vim\
    && rm -rf /var/lib/apt/lists/*
    
#Install opencv
#opencv version 3.3 because 3.4 has falty dependencies
RUN pip install opencv-python==3.3.0.9 opencv-contrib-python==3.3.0.9
#End Install opencv

#Deps opencv
RUN apt-get -y update && apt-get install -y \
    libglib2.0-0 libsm6 libxrender1 libfontconfig1 \
    libxext6 \
    && rm -rf /var/lib/apt/lists/*

#Install opencv
RUN pip install opencv-python==3.4.5.20 opencv-contrib-python==3.4.5.20
#End Install opencv
